"""Change column type to boolean

Revision ID: 1ee04fcf266c
Revises: f51f0d54897f
Create Date: 2026-06-03 15:53:53.542053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ee04fcf266c'
down_revision: Union[str, Sequence[str], None] = 'f51f0d54897f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE subscribers ALTER COLUMN subscribed TYPE BOOLEAN "
        "USING subscribed::boolean"
    )
    op.alter_column(
        'subscribers',
        'subscribed',
        nullable=False,
        server_default="true"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'subscribers',
        'subscribed',
        type_=sa.Integer(),
        nullable=True,
        postgresql_using="subscribed::integer",
    )
    # ### end Alembic commands ###
